name: DogPuter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-timeout
        pip install -e .
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb python3-pygame
    
    - name: Test with pytest
      run: |
        python -m pytest --cov=src/dogputer tests/
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
